import 'dart:core';


class AppString {

  static const String medDose='MEDDOSE';
  static const String skip='skip';
  static const String pageOne='you';
  static const String pageTow='youWill';
  static const String pageThree='do';
  static const String pageFour='welcome';
  static const String welcomeBack='welcomeBack';
  static const String email = 'email';
  static const String password = 'password';
  static const String pleaseEnterValidPassword = 'please_enter_valid_password';
  static const String pleaseEnterValidDate = 'please_enter_valid_date';
  static const String pleaseEnterValidEmail = 'please_enter_valid_email';
  static const String pleaseEnterValidName = 'please_enter_valid_name';
  static const String pleaseEnterValidPhone = 'please_enter_valid_phone';
  static const String forgetPassword = 'forgetPassword';
  static const String signIn = 'sign_in';
  static const String signUp = 'sign_up';
  static const String loginFailed = 'loginFailed';
  static const String checkMail = 'checkMail';
  static const String passwordChangedSucessfully = 'passwordChangedSucessfully';
  static const String dont_have_account = 'dont_have_account';
  static const String loginSuccessfully = 'loginSuccessfully';
  static const String registerSuccessfully = 'registerSuccessfully';
  static const String sendResetLink = 'sendResetLink';
  static const String sendResetLinkInfo = 'sendResetLinkInfo';
  static const String code = 'code';
  static const String pleaseEnterValidCode = 'pleaseEnterValidCode';
  static const String newPassword = 'newPassword';
  static const String oldPassword = 'oldPassword';
  static const String confirmPassword = 'confirmPassword';
  static const String dateOfBirth = 'dateOfBirth';
  static const String confirm ='confirm';
  static const String help ='help';
  static const String article ='article';
  static const String home ='home';
  static const String favorite ='favorite';
  static const String content ='content';
  static const String profile ='profile';
  static const String female ='female';
  static const String male ='male';
  static const String phone ='phone';
  static const String lastName ='lastName';
  static const String firstName ='firstName';
  static const String regionName ='regionName';
  static const String subRegion ='subRegion';
  static const String myBooking ='myBooking';
  static const String medicalAccounts ='medicalAccounts';
  static const String address ='address';
  static const String aboutApp ='aboutApp';
  static const String contactUs ='contactUs';
  static const String ifCan ='ifCan';
  static const String settings ='settings';
  static const String support ='support';
  static const String logOut ='logOut';
  static const String ar ='ar';
  static const String en ='en';
  static const String deleteAccount ='deleteAccount';
  static const String passwordChanged ='passwordChanged';
  static const String applicationLanguage ='applicationLanguage';
  static const String medicalRecord = 'medicalRecord';
  static const String createYourNewPassword = 'createYourNewPassword';
  static const String howDoYouFeel = 'howDoYouFeel';
  static const String whatAreYouLookingFor = 'whatAreYouLookingFor';
  static const String registerSuccess = 'Register Successfully !!';
  static const String cardiology ='cardiology';
  static const String dermatology ='dermatology';
  static const String neurology ='neurology';
  static const String pediatrics ='pediatrics';
  static const String gynecology ='gynecology';
  static const String ophthalmology ='ophthalmology';
  static const String dentist ='dentist';
  static const String otolaryngologist ='otolaryngologist';
  static const String gastroenterologist ='gastroenterologist';
  static const String generalSurgery ='generalSurgery';
  static const String hematology ='hematology';
  static const String orthopedics ='orthopedics';
  static const String psychiatry ='psychiatry';
  static const String nephrology ='nephrology';
  static const String oncology ='oncology';
  static const String pharmacies ='pharmacies';
  static const String laboratories ='laboratories';
  static const String radiologyCenters ='radiologyCenters';
  static const String healthCenters ='healthCenters';
  static const String availableTime ='availableTime';
  static const String selectAppointment ='SelectAppointment';
  static const String bookSoonestAppointment ='bookSoonestAppointment';
  static const String alwaysAreminder ='alwaysAreminder';
  static const String bookingAppointment ='bookingAppointment';
  static const String timeOfWork ='timeOfWork';
  static const String availableNow ='availableNow';
  static const String aboutDoctor ='aboutDoctor';
  static const String min ='min';
  static const String preview ='preview';
  static const String doctor ='doctor';
  static const String patient ='patient';
  static const String me ='me';
  static const String specialization ='specialization';
  static const String sections ='sections';
  static const String chooseAnImageFromTheGallery ='chooseAnImageFromTheGallery';
  static const String takeAPictureWithTheCamera ='takeAPictureWithTheCamera';
  static const String uploadAPDFFile ='uploadAPDFFile';
  static const String tellTheDoctorAboutTheSymptomsYouAreExperiencing ='tellTheDoctorAboutTheSymptomsYouAreExperiencing';
  static const String explainYourConditionOrInquiryToTheDoctorBriefly ='explainYourConditionOrInquiryToTheDoctorBriefly';
  static const String character ='character';
  static const String attachAFile ='attachAFile';
  static const String anImageHasBeenSelected ='anImageHasBeenSelected';
  static const String thePDFFileHasBeenSelected ='thePDFFileHasBeenSelected';
  static const String myConsultations ='myConsultations';






}